
proposal: proposal.tex
	pdflatex proposal.tex
	pdflatex proposal.tex
	rm *.log *.aux

proposal-v2: proposal-v2.tex
	pdflatex proposal-v2.tex
	pdflatex proposal-v2.tex
	rm *.log *.aux

clean:
	rm *.pdf

